### ISSUE TITLE
Support for Objective-C Blocks

### ISSUE THREAD

**Issue by evbo** [kivy/pyobjus#32]
Hi, I stumbled upon a dead-end working with `MCNearbyServiceAdvertiserDelegate`. One of its required delegate methods involves an `NSStackBlock`, which is not callable. Is there a work around?

```
@protocol('MCNearbyServiceAdvertiserDelegate')
    def advertiser_didReceiveInvitationFromPeer_withContext_invitationHandler_(self, 
            advertiser, peerId, context, invitationHandler):
        invitationHandler(ObjcBool(True), self.session)
```

that code results in:
`Exception TypeError: "'__NSStackBlock__' object is not callable" in 'pyobjus.pyobjus.protocol_forwardInvocation' ignored`
##

**Comment by keavin7** [comment]
I've noticed that its quite common in objective C to handle callbacks with block integration which there isn't a strategy yet for in pyobjus (however works in pyobjc).
After alot of googling / coffee/ and attempts I've pretty much exausted all possibilities to get the following to work. I'm pretty motivated to solve this as it would open alot of doors in to iOS. 


Lets say you want to authorize the health kit to read write data with an objective c call... notice the completion:^ block.

[healthStore requestAuthorizationToShareTypes:shareObjectTypes readTypes:readObjectTypes completion:^(BOOL success, NSError *error) {//Nice Fat Block O Code}];

Ok so what can you do about this??

Of the things i've tried were to pass it a raw function, which fails due to an ffi encoding error. You could autoclass you own custom class that contains a block and then pass the block as the argument, but on the python getattr on the block the code will fail. 

Here's the custom class I was using
//Blocks.h

@interface HealthAuthResult: NSObject {

}

@property BOOL issuccess;

@property BOOL didtry;

-(void) healthAuthCallbackResult:(BOOL)success andError:(NSError *) error;

//@property (nonatomic,retain) void (^healthAuthBlock)(BOOL, NSError *);
//void (^healthAuthBlock)(BOOL, NSError *);

@end


//////////////
#import "Blocks.h"

@implementation HealthAuthResult

-(void) healthAuthCallbackResult:(BOOL)success andError:(NSError *) error
{
    self.didtry = YES;
    if(success == YES)
    {
        self.issuccess = YES;
    }
    else
    {
        self.issuccess = NO;
    }
}

//-(void) configureBlock{
//    self.healthAuthBlock = ^(BOOL success, NSError *error){
//        //[self healthAuthCallbackResult:success andError:error];
//        NSLog(@"Hello This is block");
//    };
//}

void (^healthAuthBlock)(BOOL, NSError *);

@end

Any attempt to access HealthAuthResult.healthAuthBloc in python will fail. Here's the Pyobjus dump from the last attempt.

[DEBUG] -------------------------------------------------------------------------------- 
[DEBUG] __call__() configureBlock 0x101a2190 0x7c248870  
[DEBUG] --> want to call configureBlock ()  
[DEBUG] --> return def is ('v', '8', None)  
[DEBUG] --> args def is [('@', '0', None), (':', '4', None)]  
[DEBUG]  - [0] class instance 0x7c248870  
[DEBUG]  - selector is 0x101a1d26  
[DEBUG] --------------------------------------------------------------------------------  
[DEBUG] signature ensure_method --> configureBlock ('v', '8', None)  
[DEBUG] pre-zip signature: [('@', '0', None), (':', '4', None)] 
[DEBUG] array signature zip: [('@', '0', None), (':', '4', None)]  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=v, str_in_union=False)  
[DEBUG] argument ==> ('@', '0', None) 2  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=@, str_in_union=False)  
[DEBUG] argument ==> (':', '4', None) 2  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=:, str_in_union=False)  
[DEBUG] --- really call configureBlock with args () (signature is [('@', '0', None), (':', '4', None)])  
[DEBUG]    > 0: 2081754344  
[DEBUG]    > 1: 2081754348  
[INFO] return signature v  
Request Auth 
[DEBUG] --------------------------------------------------------------------------------  
[DEBUG] __call__() healthAuthBlock 0x101a2190 0x7c248870  
[DEBUG] --> want to call healthAuthBlock ()  
[DEBUG] --> return def is ('@?', '8', None)  
[DEBUG] --> args def is [('@', '0', None), (':', '4', None)]  
[DEBUG]  - [0] class instance 0x7c248870  
[DEBUG]  - selector is 0x101a1d46  
[DEBUG] --------------------------------------------------------------------------------  
[DEBUG] signature ensure_method --> healthAuthBlock ('@?', '8', None)  
[DEBUG] pre-zip signature: [('@', '0', None), (':', '4', None)]  
[DEBUG] array signature zip: [('@', '0', None), (':', '4', None)]  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=@?, str_in_union=False)  
 Exception Exception: Exception("Missing encoding for '@?'",) in 'pyobjus.pyobjus.type_encoding_to_ffitype' ignored 
[DEBUG] argument ==> ('@', '0', None) 2  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=@, str_in_union=False)  
[DEBUG] argument ==> (':', '4', None) 2  
[DEBUG] input for type_encoding_to_ffitype(type_encoding=:, str_in_union=False)


What's going on here? It looks like the type encoding isn't set right??? Does that mean that pyobjus needs to have some type of block / namespace encoding?



Has anyone solve this yet?

**Comment by akshayaurora** [comment]
One possible workaround is to write intermediate objectives files and interact with them, till this is solved in pyobjus.

**Comment by GoBig87** [comment]
Would following the AVfoundation in kivy (https://github.com/kivy/kivy/tree/master/kivy/core/camera) be a good guide for doing this?  Right now I've wrote an obj-c intermediate file  and pyx file to wrap the obj-c (https://github.com/GoBig87/Stripe_iOS_Wrapper/tree/0.1) then I cythonize it and build it for each arch and combine it into a lib.  A more in-depth breakdown can be found here https://github.com/kivy/kivy-ios/issues/292

**Comment by keavin7** [comment]
A quick follow up to this. I've found that while its most convenient from a code writing standpoint to just leverage pyobjus to use objc directly from python there are alot of time this breaks.

MY SUGGESTION:
Make a .dylib file in objc. Import this using pyobjus then you can call from some custom functions from pythohn, and get the right data you need. This has saved me alot of time and always works, but its a bit more work. 

Good Luck!

**Comment by GoBig87** [comment]
Well I'm almost through with wrapping it with obj-c with c and cython.  I've got my recipe to compile my obj-c, its just failing right now because it can't find a .h file in a third party framework (stripe).  If this path doesn't work for me I'll give the dylib route a go.  Thanks for the advice!

**Comment by mbrockman1** [comment]
If anyone has some tips or sample code I could follow, I would greatly appreciate it. I am trying to do access HealthKit data like @SoundsSerious however I'm 2 years late to the party. I am working on making a dylib file now.

**Comment by Julian-O** [comment]
This appears to be a resolved support question. Closing as stale.
